[tool.black]
line-length = 80
target-version = ['py37']
extend-exclude = '(^\./\.coverage|^\./\.target)'

[tool.coverage.run]
branch = true
parallel = true
source = ['.', './tools']
data_file = '.coverage/.coverage'

[tool.coverage.html]
directory = 'coverage/py'
